<a href="/">Come back</a>
<div>
    <img style="display: block; margin-left: auto; margin-right: auto" height="200" width="200" src="${movie.image}">
</div>
<h1 style="text-align: center">${movie.name}</h1>
<p>Description: ${movie.description}</p>
<p>Year of issue: ${movie.yearOfIssue}</p>
<p>Producer: ${movie.producer}</p>
<p>Duration: ${movie.duration} minutes</p>
<p>Age limit: ${movie.ageLimit}+</p>